# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-nodejs # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
package:
 include:
   - node_modules/**
   - ./Textile.ttf

functions:
  sunny:
    handler: handler.sunny
    events: 
      - http:
          path: sweetdee
          method: POST
    environment:
      IMGUR_CLIENT_ID:  ${file(./.serverless.env.yml):${opt:stage}.IMGUR_CLIENT_ID}